[project]
name = "container-knacker-backend"
version = "0.1.0"
description = "Backend package for container-knacker project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geneticalgorithm>=1.0.2",
    "matplotlib>=3.10.7",
    "networkx>=3.5",
    "numpy>=2.3.4",
]

